from devrt/xserver:mybuild

## apt-get install -q -qq -y xfonts-100dpi xfonts-75dpi x11-xserver-utils x11-utils \
RUN apt-get update -q -qq \
    && apt-get install -q -qq -y xfonts-100dpi xfonts-75dpi \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i -e 's@\-dpms@-dpms -fp /usr/share/fonts/X11/misc,/usr/share/fonts/X11/100dpi,/usr/share/fonts/X11/75dpi@' /app/conf.d/xvnc.conf
